# Generated by Django 4.2.5 on 2024-04-03 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_body",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="no_of_likes",
            field=models.ManyToManyField(
                blank=True, related_name="postlikes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
